## Step 1: Importing Required Libraries 

Here, I am importing the basic libraries needed for:
- Data handling (`pandas`, `numpy`)
- Getting the Iris dataset
- Splitting data
- Training and testing the model


In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


## Step 2: Loading and Exploring the Iris Dataset 

Now I load the built-in Iris dataset using `scikit-learn`.  
Then I check:
- The shape of features (X)
- The shape of target labels (y)
- First 5 values to understand the structure


In [2]:
# Cell 2: Load and explore the iris dataset

# loading the iris dataset
iris = load_iris()

# storing data and target in separate variables
X = iris.data  # features (flower measurements)
y = iris.target  # labels (flower species)

# printing shape of data and target
print("Shape of features (X):", X.shape)
print("Shape of target (y):", y.shape)

# print first 5 feature values and labels
print("\nFirst 5 rows of data:")
print(X[:5])

print("\nFirst 5 target values:")
print(y[:5])


Shape of features (X): (150, 4)
Shape of target (y): (150,)

First 5 rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 target values:
[0 0 0 0 0]


## Step 3: Splitting the Data 

I'm splitting the dataset into training and testing parts:
- 80% for training
- 20% for testing

This helps the model to learn from training data and get tested on unseen data.


In [3]:
# Splitting the dataset into training and testing parts
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Show the shapes of the train and test data
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)


Shape of X_train: (120, 4)
Shape of X_test: (30, 4)
Shape of y_train: (120,)
Shape of y_test: (30,)


## Step 4: Model Training 

Here I use Logistic Regression to train my model on training data.  

In [4]:
# Create the model
model = LogisticRegression(max_iter=200)

# Train the model on training data
model.fit(X_train, y_train)

print("Model training completed.")


Model training completed.


## Step 5: Making Predictions & Checking Accuracy 

I use the trained model to:
- Predict the flower type on test data
- Check how accurate the predictions are using `accuracy_score`

If the accuracy is 1.0, it means the model predicted all test samples correctly.


In [5]:
# Predict the labels for the test set
y_pred = model.predict(X_test)

# Print the predicted values
print("Predicted values:", y_pred)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of the model:", accuracy)


Predicted values: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy of the model: 1.0


In [6]:
print("\n✅ Task 4 completed successfully!\nThis was my first ML model using the Iris dataset.")



✅ Task 4 completed successfully!
This was my first ML model using the Iris dataset.
